"use client";

import { useState } from "react";
import { CodeBlock } from "@/components/ui/code-block";
import { cn } from "@/lib/utils";
import {
  SNIPPET_FILENAMES,
  SNIPPET_LABELS,
  SNIPPET_LANGUAGES,
  type SnippetLanguage,
} from "@/lib/integration/snippets";

/**
 * The same four snippets the dashboard's Integrate page serves, generated by
 * the same module. Nothing here is written for marketing — if the example on
 * this page and the example inside the product could drift, one of them would
 * be a lie.
 *
 * Language chips live inside the header bar rather than as a tab strip above
 * the box, so the control and the thing it controls are one object.
 */
export function Integration({ snippets }: { snippets: Record<SnippetLanguage, string> }) {
  const [language, setLanguage] = useState<SnippetLanguage>("javascript");

  return (
    <section id="integration" className="scroll-mt-14 border-b border-border">
      <div className="mx-auto max-w-[1200px] px-6 py-20">
        <div className="grid gap-10 lg:grid-cols-[minmax(0,24rem)_minmax(0,1fr)] lg:gap-16">
          <div>
            <h2 className="max-w-[20ch] text-[clamp(1.75rem,3vw,2.25rem)] font-medium leading-tight tracking-[var(--tracking-heading)]">
              One request, in whatever you already write.
            </h2>
            <p className="mt-4 max-w-[40ch] text-[14px] leading-relaxed text-fg-tertiary">
              No SDK to install and no client library to keep current. If your language can
              make an HTTPS request and parse JSON, it can verify a licence.
            </p>
          </div>

          <div className="min-w-0 overflow-hidden rounded-lg border border-border bg-surface-2">
            <div className="flex h-9 items-center gap-2 border-b border-border px-2">
              <span className="hidden truncate px-1.5 font-mono text-[12px] text-fg-quaternary sm:inline">
                {SNIPPET_FILENAMES[language]}
              </span>
              <div className="ml-auto flex items-center gap-0.5">
                {SNIPPET_LANGUAGES.map((option) => (
                  <button
                    key={option}
                    type="button"
                    onClick={() => setLanguage(option)}
                    aria-pressed={option === language}
                    className={cn(
                      "h-6 rounded-sm px-2 text-[11px] font-medium transition-colors duration-[var(--speed-quick)] focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:outline-none",
                      option === language
                        ? "bg-accent text-foreground"
                        : "text-fg-quaternary hover:text-fg-secondary",
                    )}
                  >
                    {SNIPPET_LABELS[option]}
                  </button>
                ))}
              </div>
            </div>

            <CodeBlock source={snippets[language]} language={language} />
          </div>
        </div>
      </div>
    </section>
  );
}
