import { cn } from "@/lib/utils";
import { tokenizeSnippet, type SnippetLanguage, type TokenKind } from "@/lib/integration/snippets";

/**
 * Syntax colour with no dependency.
 *
 * The four integration examples are generated by `lib/integration/snippets.ts`,
 * so the tokens can come from the same module that produced the text. A
 * highlighting library would be several hundred kilobytes to colour code we
 * wrote ourselves.
 *
 * The palette is four hues drawn from `--chart-1..3`, which have been defined
 * in both themes since Alpha_v1 and unused until now. Four is the discipline
 * the best documentation sites keep to; more than that and a snippet reads as
 * confetti.
 */
const TOKEN_CLASS: Record<TokenKind, string> = {
  plain: "text-[var(--code-plain)]",
  comment: "text-[var(--code-comment)] italic",
  keyword: "text-[var(--code-keyword)]",
  string: "text-[var(--code-string)]",
  fn: "text-[var(--code-fn)]",
  punct: "text-[var(--code-punct)]",
};

/**
 * A code body with a line-number gutter.
 *
 * Rendered as one `<pre>` per line rather than a single block so the gutter
 * can align without a table: `grid-cols-[2rem_1fr]` puts the numeral in a
 * fixed column and lets the code wrap-free-scroll in the other.
 */
export function CodeBlock({
  source,
  language,
  className,
}: {
  source: string;
  language: SnippetLanguage;
  className?: string;
}) {
  const lines = source.split("\n");

  return (
    <div className={cn("overflow-x-auto", className)}>
      <pre className="w-fit min-w-full py-3 font-mono text-[13px] leading-5">
        <code>
          {lines.map((line, index) => {
            // Tokenizing per line keeps the gutter honest. The scanner is
            // line-oriented anyway: comments terminate at a newline and the
            // only multi-line construct is a template literal, which none of
            // the four snippets uses.
            const tokens = tokenizeSnippet(line, language);

            return (
              <span key={index} className="grid grid-cols-[2.5rem_1fr] gap-0">
                <span
                  className="select-none pr-3 text-right text-[var(--code-comment)] tabular-nums"
                  aria-hidden="true"
                >
                  {index + 1}
                </span>
                <span className="pr-4">
                  {tokens.length === 0 ? (
                    " "
                  ) : (
                    tokens.map((token, position) => (
                      <span key={position} className={TOKEN_CLASS[token.kind]}>
                        {token.text}
                      </span>
                    ))
                  )}
                </span>
              </span>
            );
          })}
        </code>
      </pre>
    </div>
  );
}
